### ISSUE TITLE
Frends.JSON.ConvertToXML

### ISSUE THREAD

**Issue by ttossavainen** [FrendsPlatform/Frends.JSON2#1]

**Comment by ttossavainen** [comment]
Doesn't belong to this repo. See [Frends.JSON.ConvertXMLStringToJToken](https://github.com/FrendsPlatform/Frends.JSON2/blob/main/Frends.JSON.ConvertXMLStringToJToken/README.md)

**Comment by jefim** [comment]
Actually we still do not have a JSON to XML conversion :)

**Comment by RikuVirtanen** [comment]
This Task has been implemented in the correct repo: https://github.com/FrendsPlatform/Frends.CrossplatformXML/pull/23
