### ISSUE TITLE
Frends.JSON.Handlebars bug in import

### ISSUE THREAD

**Issue by RikuVirtanen** [FrendsPlatform/Frends.JSON2#19]
Error is thrown when trying to import the task to Frends. 
![image](https://user-images.githubusercontent.com/66992970/223998323-d1600cd6-4db8-44fb-80e5-83456d68c2e2.png)

**Comment by ttossavainen** [comment]
Have to use local ref for Handlebars.

**Comment by ttossavainen** [comment]
merged
