### ISSUE TITLE
ConvertJSONStringToJToken: Cannot access values in resulted JToken

### ISSUE THREAD

**Issue by Svenskapojkarna** [FrendsPlatform/Frends.JSON2#24]
If you parse JSON string using this Task then you cannot access any values in the JToken.
Trying to access values in the JToken causes compilation error.
![image](https://github.com/FrendsPlatform/Frends.JSON2/assets/36008914/dd6b721a-26a3-41b6-b392-48522a6c31e1)

Steps to reproduce:

1. Parse a JSON string using this Task. 
![image](https://github.com/FrendsPlatform/Frends.JSON2/assets/36008914/1fb2df0f-5364-4314-8924-e2bb70fe1576)
2. Save any of the properties to a variable.
![image](https://github.com/FrendsPlatform/Frends.JSON2/assets/36008914/5daae414-debf-4b4b-96bc-0390854a820e)
3. Try to save the process.

**Comment by RikuVirtanen** [comment]
The Task's result Jtoken type is object and needs to be changed to dynamic so that Frends can handle the JToken value with dotnotation.
